spring.datasource.url=jdbc:mysql://localhost/order_service_microservice_springboot_data?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.file.name=logs/application.log
server.port=8081
NOTIFICATION_SERVICE_URL=http://localhost:8082