###
POST localhost:8080/telegram/message/630591809?message=Hello World!



###
POST localhost:8080/telegram/document/804476257 HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="3.xlsx"

// The 'input.txt' file will be uploaded
< C:\Users\User\Desktop\3.xlsx

POST localhost:8080/telegram/image/804476257 HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="3.xlsx"

// The 'input.txt' file will be uploaded
< C:\Users\User\Desktop\12.png

POST localhost:8080/telegram/audio/804476257 HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="3.xlsx"

// The 'input.txt' file will be uploaded
< C:\Users\User\Desktop\2.mp3